spring:
  application:
    name: sellary

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jasypt:
  encryptor:
    password: EXIT_DAOU_2025#@!