name: Deploy to EC2 on main merge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./sellary-backend/gradlew clean build

      - name: Upload JAR to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_WAS }}
          EC2_USER: ${{ secrets.EC2_HOST }}
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          scp -i key.pem -o StrictHostKeyChecking=no build/libs/your-app.jar $EC2_USER@$EC2_HOST:/home/service/binary/

